"""add reinforcement time

Revision ID: 83a1946ee503
Revises: d8e2eeb29dd5
Create Date: 2017-09-19 19:40:07.608139

"""

# revision identifiers, used by Alembic.
revision = '83a1946ee503'
down_revision = 'd8e2eeb29dd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('reinforced_at_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play', 'reinforced_at_time')
    ### end Alembic commands ###
