"""initial

Revision ID: c59f6984550b
Revises: 
Create Date: 2017-09-18 14:42:58.514802

"""

# revision identifiers, used by Alembic.
revision = 'c59f6984550b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_track'))
    )
    op.create_table('play',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('track', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('mood', sa.String(length=1024), nullable=False),
    sa.Column('positive_feedback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['track'], ['track.uuid'], name=op.f('fk_play_track_track')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_play'))
    )
    op.create_table('track_location',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('track', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['track'], ['track.uuid'], name=op.f('fk_track_location_track_track')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_track_location'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_location')
    op.drop_table('play')
    op.drop_table('track')
    ### end Alembic commands ###
